Repository swyp-fade/fade-api, pull requests merged in 2024-08, with the labels that each got.

#113 fix: profileImage null 처리 메서드 적용, 구독자 수 처리 수정, 커서 조건 추가
  src/main/java/com/fade/faparchiving/service/FapArchivingService.java
  src/main/java/com/fade/feed/dto/response/FindFeedDetailResponse.java
  src/main/java/com/fade/feed/dto/response/FindFeedResponse.java
  src/main/java/com/fade/feed/service/FeedService.java
  src/main/java/com/fade/subscribe/dto/response/FindSubscriberResponse.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepositoryCustom.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepositoryImpl.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: bug, enhancement

#114 fix: 투표 내역 조회 커서 오류 수정(파라미터 기본값 추가, 기존 커서 방식과 동일하게 변경)
  src/main/java/com/fade/vote/controller/VoteController.java
  src/main/java/com/fade/vote/dto/request/FindVoteRequest.java
  src/main/java/com/fade/vote/dto/response/FindVoteResponse.java
  src/main/java/com/fade/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/fade/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: bug, enhancement

#115 fix: 알림 커서 수정
  src/main/java/com/fade/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/fade/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/fade/notification/service/NotificationService.java
Labels: bug, enhancement

#116 fix: 아카이빙 스타일 id 값 필드명 수정
  src/main/java/com/fade/faparchiving/dto/response/FindFapArchivingResponse.java
Labels: bug, enhancement

#117 fetchType별 피드 조회 스크롤, fadeInCount, 멤버 검색 DTO 수정
  src/main/java/com/fade/faparchiving/service/FapArchivingService.java
  src/main/java/com/fade/feed/controller/FeedController.java
  src/main/java/com/fade/feed/dto/request/FindNextFeedCursorRequest.java
  src/main/java/com/fade/feed/repository/CustomFeedRepository.java
  src/main/java/com/fade/feed/repository/impl/FeedRepositoryImpl.java
  src/main/java/com/fade/feed/service/FeedService.java
  src/main/java/com/fade/member/dto/response/MemberSearchResponse.java
  src/main/java/com/fade/vote/dto/request/CountVoteRequest.java
  src/main/java/com/fade/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/fade/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: bug, enhancement

#118 feat: 소셜 회원가입시 프로필 이미지 가져오기
  src/main/java/com/fade/attachment/entity/Attachment.java
  src/main/java/com/fade/attachment/service/AttachmentService.java
  src/main/java/com/fade/global/CustomMultipartFile.java
  src/main/java/com/fade/global/component/FileUploader.java
  src/main/java/com/fade/global/component/impl/KakaoOAuth2Provider.java
  src/main/java/com/fade/global/component/impl/S3FileUploader.java
  src/main/java/com/fade/global/dto/OAuthProfile.java
  src/main/java/com/fade/member/dto/request/ModifyMemberRequest.java
  src/main/java/com/fade/sociallogin/service/SocialLoginService.java
Labels: enhancement

#120 fix: 투표 목록에서 내 피드 반환되는 이슈 수정
  src/main/java/com/fade/feed/repository/impl/FeedRepositoryImpl.java
Labels: bug, enhancement

#121 fix: 내가 구독한 구독자 수 가져올 때 where조건절 빠진거 수정
  src/main/java/com/fade/feed/service/FeedService.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepositoryCustom.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepositoryImpl.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
Labels: bug

#122 feat: refresh token cookie 없을 때도 잘 작동 하도록 수정
  src/main/java/com/fade/auth/controller/AuthController.java
  src/main/java/com/fade/auth/dto/request/TokenRenewRequest.java
  src/main/java/com/fade/auth/dto/response/HttpSigninInResponse.java
Labels: bug, enhancement

#124 feat: 유저 정보 수정 Patch 메서드로 수정 및 피드 수정 Patch 메서드 구현
  src/main/java/com/fade/feed/controller/FeedController.java
  src/main/java/com/fade/feed/dto/request/ModifyFeedRequest.java
  src/main/java/com/fade/feed/entity/Feed.java
  src/main/java/com/fade/feed/entity/FeedOutfit.java
  src/main/java/com/fade/feed/repository/FeedOutfitRepository.java
  src/main/java/com/fade/feed/service/FeedService.java
  src/main/java/com/fade/member/controller/MemberController.java
Labels: enhancement

#125 feat: username regexp 숫자 0 안되는 이슈 해결
  src/main/java/com/fade/member/constant/MemberRegexp.java
Labels: bug

#126 fix: 피드 수정 권한 조건문 실수 수정
  src/main/java/com/fade/feed/service/FeedService.java
Labels: bug

#129 feat: 프로필 이미지 변경 DTO 필드명 수정
  src/main/java/com/fade/member/dto/request/ModifyMemberRequest.java
  src/main/java/com/fade/member/service/MemberService.java
Labels: enhancement

#128 feat: report 타입 추가
  src/main/java/com/fade/report/constant/ReportType.java
  src/main/java/com/fade/report/controller/ReportController.java
  src/main/java/com/fade/report/dto/request/CreateReportRequest.java
  src/main/java/com/fade/report/entity/Report.java
  src/main/java/com/fade/report/service/ReportService.java
Labels: enhancement

#127 feat: 리소스 url cloudfront 태우기
  src/main/java/com/fade/attachment/service/AttachmentService.java
  src/main/resources/application-common.yml
Labels: enhancement

#130 feat: swaggersummary 작성
  src/main/java/com/fade/attachment/controller/AttachmentController.java
  src/main/java/com/fade/auth/controller/AuthController.java
  src/main/java/com/fade/category/controller/CategoryController.java
  src/main/java/com/fade/feed/controller/FeedController.java
  src/main/java/com/fade/member/controller/MemberController.java
  src/main/java/com/fade/notification/controller/NotificationController.java
  src/main/java/com/fade/report/controller/ReportController.java
  src/main/java/com/fade/subscribe/controller/SubscribeController.java
Labels: documentation

#131 feat: 투표 API 스웨거 명세 설명 추가
  src/main/java/com/fade/vote/controller/VoteController.java
Labels: documentation, enhancement

#134 fix: 투표 내역 API deleted_at 조건 추가 및 nextScroll 본인 투표 조건 추가
  src/main/java/com/fade/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/fade/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: bug, enhancement

#136 fix: 투표 내역 DTO memberId 추가
  src/main/java/com/fade/vote/dto/response/FindVoteResponse.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: bug, enhancement

#133 feat: member 수정 API genderType 수정
  src/main/java/com/fade/member/dto/request/ModifyMemberRequest.java
  src/main/java/com/fade/member/entity/Member.java
  src/main/java/com/fade/member/service/MemberService.java
Labels: enhancement

#123 Feature/member delete fap count
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepository.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryCustom.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryImpl.java
  src/main/java/com/fade/member/dto/response/FindMyMemberDetailResponse.java
  src/main/java/com/fade/member/service/MemberService.java
  src/main/java/com/fade/notification/service/NotificationService.java
Labels: enhancement

#137 fix: styleIds 빈 리스트 일때 처리
  src/main/java/com/fade/feed/dto/request/CreateFeedRequest.java
  src/main/java/com/fade/feed/service/FeedService.java
Labels: bug, enhancement

#138 fix: checksum 업로드 성공 상태인 리소스만 검사
  src/main/java/com/fade/attachment/repository/AttachmentRepository.java
  src/main/java/com/fade/attachment/service/AttachmentService.java
Labels: bug

#139 fix: 스케쥴러 컨텍스트에서 알림 save 안되는 이슈 해결
  src/main/java/com/fade/faparchiving/schedular/FapArchivingScheduler.java
  src/main/java/com/fade/global/config/AsyncConfig.java
  src/main/java/com/fade/notification/listener/NotificationListener.java
Labels: bug, enhancement

#140 fix: fetchType에 맞는 createdAt 반환되게 수정
  src/main/java/com/fade/bookmark/repository/BookmarkRepository.java
  src/main/java/com/fade/feed/service/FeedService.java
Labels: enhancement

#141 fix: 클라이언트 DTO와 동일하게
  src/main/java/com/fade/feed/dto/request/FindFeedRequest.java
  src/main/java/com/fade/feed/repository/impl/FeedRepositoryImpl.java
Labels: enhancement

#142 feat: Member Username unique 처리
  src/main/java/com/fade/global/constant/ErrorCode.java
  src/main/java/com/fade/member/entity/Member.java
  src/main/java/com/fade/member/repository/MemberRepository.java
  src/main/java/com/fade/member/service/MemberService.java
Labels: bug

#143 feat: 이미 존재하는 exception code 사용
  src/main/java/com/fade/global/constant/ErrorCode.java
  src/main/java/com/fade/member/service/MemberService.java
Labels: enhancement

#144 fix: 북마크 조회 오류 수정
  src/main/java/com/fade/bookmark/repository/BookmarkRepository.java
  src/main/java/com/fade/feed/service/FeedService.java
Labels: bug, enhancement

#145 fix: fetchType 북마크 일때 정렬 추가 및 타입에 따른 커서 정렬 로직 추가
  src/main/java/com/fade/bookmark/entity/Bookmark.java
  src/main/java/com/fade/feed/repository/impl/FeedRepositoryImpl.java
  src/main/java/com/fade/feed/service/FeedService.java
Labels: bug, enhancement

#146 fix: 북마크 createdAt 원래 방식으로 수정
  src/main/java/com/fade/feed/repository/impl/FeedRepositoryImpl.java
  src/main/java/com/fade/feed/service/FeedService.java
Labels: bug

#149 fix: 탈퇴한 계정 재로그인 시 탈퇴 처리 구현
  src/main/java/com/fade/global/constant/ErrorCode.java
  src/main/java/com/fade/member/repository/MemberRepository.java
  src/main/java/com/fade/member/repository/MemberSearchRepository.java
  src/main/java/com/fade/member/service/MemberService.java
Labels: bug, enhancement

#151 fix: 아카이빙 조회 시 삭제된 사진 처리 추가
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryImpl.java
  src/main/java/com/fade/faparchiving/service/FapArchivingService.java
Labels: bug, enhancement
