Repository swyp-fade/fade-api, pull requests merged in 2024-07, with the labels that each got.

#3 커스텀 Response, Exception 정의
  build.gradle
  src/main/java/com/fade/global/constant/ErrorCode.java
  src/main/java/com/fade/global/dto/response/Response.java
  src/main/java/com/fade/global/exception/ApplicationException.java
  src/main/java/com/fade/global/exception/GlobalExceptionAdvice.java
Labels: enhancement

#5 Jpa 의존성 추가
  build.gradle
Labels: enhancement

#6 투표 엔티티 구현
  src/main/java/com/fade/vote/constant/VoteType.java
  src/main/java/com/fade/vote/dto/request/VoteItemRequest.java
  src/main/java/com/fade/vote/dto/request/VoteRequest.java
  src/main/java/com/fade/vote/entity/Vote.java
Labels: enhancement

#7 DB 설정 추가 및 yml 작성
  build.gradle
  src/main/resources/application.yml
Labels: enhancement

#8 투표 컨트롤러 추가
  src/main/java/com/fade/vote/controller/VoteController.java
Labels: enhancement

#17 투표 생성 API Swagger 적용, DTO 수정, 유저, 피드 엔티티 연결
  src/main/java/com/fade/vote/controller/VoteController.java
  src/main/java/com/fade/vote/dto/request/CreateVoteRequest.java
  src/main/java/com/fade/vote/dto/request/VoteItemRequest.java
  src/main/java/com/fade/vote/dto/request/VoteRequest.java
  src/main/java/com/fade/vote/dto/response/CreateVoteResponse.java
  src/main/java/com/fade/vote/entity/Vote.java
Labels: enhancement

#20 투표 레포지토리 정의
  src/main/java/com/fade/vote/repository/VoteRepository.java
Labels: feature

#21 투표 타입(Enum) Validation 적용
  src/main/java/com/fade/global/exception/GlobalExceptionAdvice.java
  src/main/java/com/fade/vote/constant/VoteType.java
  src/main/java/com/fade/vote/controller/VoteController.java
  src/main/java/com/fade/vote/dto/request/CreateVoteRequest.java
  src/main/java/com/fade/vote/validation/VoteTypeValidation.java
  src/main/java/com/fade/vote/validation/validator/VoteTypeValidator.java
  src/main/resources/application.yml
Labels: feature

#35 feat: 피드 생성 API 추가
  .gitignore
  build.gradle
  src/main/java/com/fade/attachment/controller/AttachmentController.java
  src/main/java/com/fade/attachment/dto/request/ExistsAttachmentRequest.java
  src/main/java/com/fade/attachment/dto/request/GeneratePresignURLRequest.java
  src/main/java/com/fade/attachment/dto/response/ExistsAttachmentResponse.java
  src/main/java/com/fade/attachment/entity/Attachment.java
  src/main/java/com/fade/attachment/entity/AttachmentLink.java
  src/main/java/com/fade/attachment/repository/AttachmentLinkRepository.java
  src/main/java/com/fade/attachment/repository/AttachmentRepository.java
  src/main/java/com/fade/attachment/service/AttachmentCommonService.java
  src/main/java/com/fade/attachment/service/AttachmentService.java
  src/main/java/com/fade/bookmark/controller/BookmarkController.java
  src/main/java/com/fade/bookmark/service/BookmarkService.java
  src/main/java/com/fade/category/repository/CategoryRepository.java
  src/main/java/com/fade/category/service/CategoryCommonService.java
  src/main/java/com/fade/config/EnvConfiguration.java
  src/main/java/com/fade/config/S3Config.java
  src/main/java/com/fade/feed/controller/FeedController.java
  src/main/java/com/fade/feed/dto/request/CreateFeedRequest.java
  src/main/java/com/fade/feed/entity/Feed.java
  src/main/java/com/fade/feed/entity/FeedOutfit.java
  src/main/java/com/fade/feed/repository/FeedRepository.java
  src/main/java/com/fade/feed/service/FeedService.java
  src/main/java/com/fade/global/component/FileUtils.java
  src/main/java/com/fade/global/component/PresignUrlGenerator.java
  src/main/java/com/fade/global/component/impl/S3PresignUrlGenerator.java
  src/main/java/com/fade/global/constant/ErrorCode.java
  src/main/java/com/fade/member/repository/MemberRepository.java
  src/main/java/com/fade/member/service/MemberCommonService.java
  src/main/java/com/fade/style/repository/StyleRepository.java
  src/main/java/com/fade/style/service/StyleCommonService.java
  src/main/resources/application.yml
Labels: enhancement

#32 투표 생성 API 개발(Member, Feed 연결 X)
  src/main/java/com/fade/vote/service/VoteService.java
Labels: feature

#39 투표 생성 API 개발 (피드 - 유저 - 투표 연결)
  src/main/java/com/fade/feed/exception/FeedNotFoundException.java
  src/main/java/com/fade/feed/service/FeedCommonService.java
  src/main/java/com/fade/global/constant/ErrorCode.java
  src/main/java/com/fade/global/exception/GlobalExceptionAdvice.java
  src/main/java/com/fade/vote/controller/VoteController.java
  src/main/java/com/fade/vote/exception/DuplicateVoteException.java
  src/main/java/com/fade/vote/repository/VoteRepository.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: enhancement

#42 유저 팔로워 / 팔로잉 (구독) API 개발
  src/main/java/com/fade/global/dto/response/Response.java
  src/main/java/com/fade/subscribe/controller/SubscribeController.java
  src/main/java/com/fade/subscribe/entity/Subscribe.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepository.java
  src/main/java/com/fade/subscribe/service/SubscribeCommonService.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
Labels: enhancement, feature

#43 feat: #30 북마크 생성, 취소 기능 구현
  src/main/java/com/fade/bookmark/controller/BookmarkController.java
  src/main/java/com/fade/bookmark/dto/BookmarkDto.java
  src/main/java/com/fade/bookmark/dto/BookmarkRequestDto.java
  src/main/java/com/fade/bookmark/dto/BookmarkResponseDto.java
  src/main/java/com/fade/bookmark/entity/Bookmark.java
  src/main/java/com/fade/bookmark/exception/BookmarkNotFoundException.java
  src/main/java/com/fade/bookmark/repository/BookmarkMemberRepository.java
  src/main/java/com/fade/bookmark/repository/BookmarkRepository.java
  src/main/java/com/fade/bookmark/service/BookmarkCommonService.java
  src/main/java/com/fade/bookmark/service/BookmarkService.java
Labels: enhancement

#45 chore: queryDsl 설정 추가
  .gitignore
  build.gradle
Labels: enhancement, feature

#46 feat: cors 설정
  src/main/java/com/fade/global/config/SecurityConfig.java
  src/main/resources/application.yml
Labels: enhancement

#47 feat: #44 투표 내역 No-offset 스크롤 서비스 로직 구현
  src/main/java/com/fade/vote/controller/VoteController.java
  src/main/java/com/fade/vote/dto/response/FindVoteResponse.java
  src/main/java/com/fade/vote/repository/VoteRepository.java
  src/main/java/com/fade/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/fade/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: enhancement, feature

#52 feat: 투표, 북마크, 구독 유저 인증 Header 적용
  src/main/java/com/fade/bookmark/controller/BookmarkController.java
  src/main/java/com/fade/subscribe/controller/SubscribeController.java
  src/main/java/com/fade/vote/controller/VoteController.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: enhancement

#55 에러 처리 핸들러 추가
  src/main/java/com/fade/global/component/impl/KakaoOAuth2Provider.java
  src/main/java/com/fade/global/constant/ErrorCode.java
  src/main/java/com/fade/global/exception/GlobalExceptionAdvice.java
Labels: bug, enhancement

#54 feat: #53 일별 FADE 집계 비즈니스 로직 구현
  src/main/java/com/fade/FadeApplication.java
  src/main/java/com/fade/vote/controller/VoteController.java
  src/main/java/com/fade/vote/dto/FindDailyPopularFeedDto.java
  src/main/java/com/fade/vote/dto/response/FindMonthlyPopularFeedArchivingResponse.java
  src/main/java/com/fade/vote/entity/DailyPopularFeedArchiving.java
  src/main/java/com/fade/vote/repository/DailyPopularFeedArchivingRepository.java
  src/main/java/com/fade/vote/repository/DailyPopularFeedArchivingRepositoryCustom.java
  src/main/java/com/fade/vote/repository/DailyPopularFeedArchivingRepositoryImpl.java
  src/main/java/com/fade/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/fade/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/fade/vote/schedular/VoteScheduler.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: enhancement, feature

#59 feat:#56 구독 피드 조회 기능 추가
  src/main/java/com/fade/feed/repository/CustomFeedRepository.java
  src/main/java/com/fade/feed/repository/impl/FeedRepositoryImpl.java
  src/main/java/com/fade/subscribe/controller/SubscribeController.java
  src/main/java/com/fade/subscribe/dto/request/FindSubscribeFeedRequest.java
  src/main/java/com/fade/subscribe/dto/response/FindSubscribeFeedResponse.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepository.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
  src/main/java/com/fade/vote/repository/DailyPopularFeedArchivingRepository.java
Labels: enhancement, feature

#62 feat:#56 구독자 목록 조회 API 구현
  src/main/java/com/fade/subscribe/controller/SubscribeController.java
  src/main/java/com/fade/subscribe/dto/request/FindSubscriberRequest.java
  src/main/java/com/fade/subscribe/dto/response/FindSubscriberResponse.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepository.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepositoryCustom.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepositoryImpl.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
Labels: enhancement, feature

#58 feat: refreshToken 쿠키에 저장
  src/main/java/com/fade/auth/controller/AuthController.java
  src/main/java/com/fade/auth/dto/response/CreateAccessTokenByRefreshTokenResponse.java
  src/main/java/com/fade/auth/dto/response/HttpSigninInResponse.java
  src/main/java/com/fade/auth/service/AuthService.java
  src/main/java/com/fade/global/config/SecurityConfig.java
  src/main/java/com/fade/global/constant/ErrorCode.java
  src/main/java/com/fade/member/service/MemberService.java
  src/main/java/com/fade/member/vo/UserVo.java
  src/main/java/com/fade/sociallogin/service/SocialLoginService.java
Labels: enhancement

#66 feat:#64 알림 엔티티, DTO, 알림 생성 구현
  src/main/java/com/fade/notification/constant/NotificationStatus.java
  src/main/java/com/fade/notification/constant/NotificationType.java
  src/main/java/com/fade/notification/dto/CreateNotificationDto.java
  src/main/java/com/fade/notification/entity/Notification.java
  src/main/java/com/fade/notification/listener/NotificationListener.java
  src/main/java/com/fade/notification/repository/NotificationRepository.java
  src/main/java/com/fade/notification/service/NotificationService.java
Labels: enhancement, feature

#69 Feature/#67 알림 조회 스크롤, 페이피 알림 생성 API 구현
  src/main/java/com/fade/notification/constant/NotificationStatus.java
  src/main/java/com/fade/notification/constant/NotificationType.java
  src/main/java/com/fade/notification/controller/NotificationController.java
  src/main/java/com/fade/notification/dto/CreateNotificationDto.java
  src/main/java/com/fade/notification/dto/request/FindNotificationRequest.java
  src/main/java/com/fade/notification/dto/response/FindNotificationResponse.java
  src/main/java/com/fade/notification/entity/Notification.java
  src/main/java/com/fade/notification/repository/NotificationRepository.java
  src/main/java/com/fade/notification/repository/NotificationRepositoryCustom.java
  src/main/java/com/fade/notification/repository/NotificationRepositoryImpl.java
  src/main/java/com/fade/notification/service/NotificationService.java
  src/main/java/com/fade/vote/entity/DailyPopularFeedArchiving.java
  src/main/java/com/fade/vote/schedular/VoteScheduler.java
Labels: enhancement

#71 refactor:#70 기존 페이피 아카이빙 패키지 구조 수정, 엔티티 명 변경, 그에 따른 변경 사항 등
  src/main/java/com/fade/faparchiving/controller/FapArchivingController.java
  src/main/java/com/fade/faparchiving/dto/response/FindFapArchivingResponse.java
  src/main/java/com/fade/faparchiving/entity/FapArchiving.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepository.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryCustom.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryImpl.java
  src/main/java/com/fade/faparchiving/schedular/FapArchivingScheduler.java
  src/main/java/com/fade/faparchiving/service/FapArchivingService.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
  src/main/java/com/fade/vote/controller/VoteController.java
  src/main/java/com/fade/vote/dto/FindMostVoteItemDto.java
  src/main/java/com/fade/vote/dto/response/FindMonthlyPopularFeedArchivingResponse.java
  src/main/java/com/fade/vote/repository/DailyPopularFeedArchivingRepository.java
  src/main/java/com/fade/vote/repository/DailyPopularFeedArchivingRepositoryCustom.java
  src/main/java/com/fade/vote/repository/DailyPopularFeedArchivingRepositoryImpl.java
  src/main/java/com/fade/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/fade/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/fade/vote/schedular/VoteScheduler.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: enhancement

#72 계정 검색 api
  src/main/java/com/fade/member/controller/MemberSearchController.java
  src/main/java/com/fade/member/dto/response/MemberSearchResponse.java
  src/main/java/com/fade/member/repository/MemberSearchRepository.java
  src/main/java/com/fade/member/service/MemberSearchService.java
  src/main/resources/application.yml
Labels: enhancement, feature

#65 피드 조회 API, Request 쿼리 파라미터 추가
  src/main/java/com/fade/feed/controller/FeedController.java
  src/main/java/com/fade/feed/dto/request/FindFeedRequest.java
  src/main/java/com/fade/feed/repository/CustomFeedRepository.java
  src/main/java/com/fade/feed/repository/impl/FeedRepositoryImpl.java
  src/main/java/com/fade/feed/service/FeedService.java
  src/main/java/com/fade/global/constant/SortType.java
  src/main/java/com/fade/style/entity/Style.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
Labels: enhancement

#73 feat: subscirbe controller에 feed list api 삭제
  src/main/java/com/fade/feed/dto/request/FindSubscribeFeedRequest.java
  src/main/java/com/fade/feed/dto/response/FindSubscribeFeedResponse.java
  src/main/java/com/fade/subscribe/controller/SubscribeController.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
Labels: enhancement

#75 feat: member search api permitAll
  src/main/java/com/fade/global/config/SecurityConfig.java
  src/main/java/com/fade/global/constant/ErrorCode.java
Labels: enhancement

#76 멤버서치 수정
  src/main/java/com/fade/member/controller/MemberController.java
  src/main/java/com/fade/member/dto/response/MemberSearchResult.java
  src/main/java/com/fade/member/repository/MemberSearchRepository.java
  src/main/java/com/fade/member/service/MemberService.java
Labels: enhancement

#79 Refactor/#74 Vote, Subscribe, Notification, Archiving DTO 정보 수정
  src/main/java/com/fade/bookmark/repository/BookmarkRepository.java
  src/main/java/com/fade/faparchiving/controller/FapArchivingController.java
  src/main/java/com/fade/faparchiving/dto/response/FindFapArchivingResponse.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepository.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryImpl.java
  src/main/java/com/fade/faparchiving/service/FapArchivingService.java
  src/main/java/com/fade/feed/dto/response/ExtractRandomFeedResponse.java
  src/main/java/com/fade/notification/dto/response/FindNotificationResponse.java
  src/main/java/com/fade/notification/service/NotificationService.java
  src/main/java/com/fade/subscribe/controller/SubscribeController.java
  src/main/java/com/fade/subscribe/dto/response/FindSubscriberResponse.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepository.java
  src/main/java/com/fade/vote/dto/response/FindVoteResponse.java
  src/main/java/com/fade/vote/repository/VoteRepositoryCustom.java
  src/main/java/com/fade/vote/repository/VoteRepositoryImpl.java
  src/main/java/com/fade/vote/service/VoteService.java
  src/main/resources/application.yml
Labels: enhancement

#80 refactor: #74 투표,구독,알림,페이피 dto 명명 및 구조 변경 이에 대응하는 코드 변경
  src/main/java/com/fade/vote/dto/response/FindVoteResponse.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: enhancement

#82 feat: 피드 신고 API
  src/main/java/com/fade/feed/entity/Feed.java
  src/main/java/com/fade/global/constant/ErrorCode.java
  src/main/java/com/fade/report/controller/ReportController.java
  src/main/java/com/fade/report/dto/request/CountReportRequest.java
  src/main/java/com/fade/report/dto/request/CreateReportRequest.java
  src/main/java/com/fade/report/dto/response/CreateReportResponse.java
  src/main/java/com/fade/report/entity/Report.java
  src/main/java/com/fade/report/repository/CustomReportRepository.java
  src/main/java/com/fade/report/repository/ReportRepository.java
  src/main/java/com/fade/report/repository/impl/CustomReportRepositoryIml.java
  src/main/java/com/fade/report/service/ReportService.java
Labels: enhancement

#85 feat: member jwt claim에 성별, username 추가
  src/main/java/com/fade/auth/service/AuthService.java
  src/main/java/com/fade/global/filter/JwtFilter.java
  src/main/java/com/fade/member/service/MemberService.java
  src/main/java/com/fade/member/vo/MemberJwtClaim.java
  src/main/java/com/fade/member/vo/UserVo.java
Labels: enhancement

#86 feat: #83 신고 알림 기능, 페이피 삭제 알림 기능 구현
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryCustom.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryImpl.java
  src/main/java/com/fade/faparchiving/schedular/FapArchivingScheduler.java
  src/main/java/com/fade/feed/controller/FeedController.java
  src/main/java/com/fade/feed/entity/Feed.java
  src/main/java/com/fade/feed/service/FeedService.java
  src/main/java/com/fade/notification/dto/CreateNotificationDto.java
  src/main/java/com/fade/notification/dto/response/FindNotificationResponse.java
  src/main/java/com/fade/notification/entity/Notification.java
  src/main/java/com/fade/notification/service/NotificationService.java
  src/main/java/com/fade/report/entity/Report.java
  src/main/java/com/fade/report/repository/ReportRepository.java
  src/main/java/com/fade/report/service/ReportService.java
Labels: enhancement

#88 feat: #87 토큰 발급 테스트용 로그인 API 구현
  src/main/java/com/fade/member/controller/MemberController.java
Labels: enhancement

#89 feat: 구독 상태 체크 api 구현
  src/main/java/com/fade/subscribe/controller/SubscribeController.java
  src/main/java/com/fade/subscribe/dto/response/CheckSubscribeResponse.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
Labels: enhancement

#90 팔로잉/팔로워 수 조회 API, member 상세 API 조회 개발
  src/main/java/com/fade/member/controller/MemberController.java
  src/main/java/com/fade/subscribe/controller/SubscribeController.java
  src/main/java/com/fade/subscribe/dto/request/CountSubscriberRequest.java
  src/main/java/com/fade/subscribe/dto/response/CountSubscriberResponse.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepositoryCustom.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepositoryImpl.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
Labels: enhancement

#91 feat: 조회 API swagger content 추가
  src/main/java/com/fade/subscribe/controller/SubscribeController.java
Labels: enhancement

#92 refactor: 카테고리 dto 필드 수정 -> Integer
  src/main/java/com/fade/category/controller/CategoryController.java
  src/main/java/com/fade/category/dto/response/FindCategoryListResponse.java
  src/main/java/com/fade/faparchiving/dto/response/FindFapArchivingResponse.java
  src/main/java/com/fade/faparchiving/service/FapArchivingService.java
  src/main/java/com/fade/feed/dto/response/ExtractRandomFeedResponse.java
  src/main/java/com/fade/feed/dto/response/FindFeedResponse.java
  src/main/java/com/fade/feed/service/FeedService.java
  src/main/java/com/fade/vote/dto/response/FindVoteResponse.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: enhancement

#93 feat: feed 신고 누적 count
  src/main/java/com/fade/feed/dto/response/FindFeedDetailResponse.java
  src/main/java/com/fade/feed/dto/response/FindFeedResponse.java
  src/main/java/com/fade/feed/service/FeedService.java
  src/main/java/com/fade/report/repository/impl/CustomReportRepositoryImpl.java
Labels: enhancement

#94 feat: token 재발급 API refreshToken 없으면 UNAUTHORIZED
  src/main/java/com/fade/auth/controller/AuthController.java
Labels: enhancement

#95 feat: cookie-samesite 설정 추가
  src/main/java/com/fade/auth/controller/AuthController.java
  src/main/java/com/fade/auth/dto/response/ResponseCookie.java
Labels: enhancement

#96 feat: 반환 형식 수정
  src/main/java/com/fade/auth/controller/AuthController.java
Labels: enhancement

#97 fix: 로그인 서비스 Transaction 처리
  src/main/java/com/fade/auth/controller/AuthController.java
  src/main/java/com/fade/auth/service/AuthService.java
Labels: enhancement

#98 fix: datetime 파싱 에러 수정
  src/main/java/com/fade/faparchiving/constant/DateTimeRegexp.java
  src/main/java/com/fade/faparchiving/controller/FapArchivingController.java
Labels: enhancement

#99 fix: 운영서버 스웨거 호출 URL이슈 해결
  src/main/java/com/fade/global/config/SecurityConfig.java
  src/main/java/com/fade/global/config/SwaggerConfig.java
  src/main/resources/application-common.yml
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.yml
Labels: enhancement

#100 feat: 로그아웃 API 개발
  src/main/java/com/fade/auth/controller/AuthController.java
  src/main/java/com/fade/auth/service/AuthService.java
  src/main/java/com/fade/member/repository/RefreshTokenRepository.java
Labels: enhancement

#101 fix: 피드 styles 테이블 manytomany 컬럼 거꾸로 되어 있는 부분 수정
  src/main/java/com/fade/feed/entity/Feed.java
Labels: bug

#102 refactor: feed dto createdAt 추가
  src/main/java/com/fade/feed/dto/response/ExtractRandomFeedResponse.java
  src/main/java/com/fade/feed/dto/response/FindFeedDetailResponse.java
  src/main/java/com/fade/feed/dto/response/FindFeedResponse.java
  src/main/java/com/fade/feed/service/FeedService.java
  src/main/java/com/fade/vote/service/VoteService.java
Labels: enhancement

#103 refactor: fadeInCount, createdAt 추가
  src/main/java/com/fade/faparchiving/dto/response/FindFapArchivingResponse.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryCustom.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryImpl.java
  src/main/java/com/fade/faparchiving/service/FapArchivingService.java
  src/main/java/com/fade/feed/dto/response/FindFeedDetailResponse.java
  src/main/java/com/fade/feed/dto/response/FindFeedResponse.java
  src/main/java/com/fade/feed/service/FeedService.java
Labels: enhancement

#104 refactor: 무한 스크롤 nextCursor 반환 or null 로 수정
  src/main/java/com/fade/feed/dto/response/FindFeedResponse.java
  src/main/java/com/fade/feed/repository/CustomFeedRepository.java
  src/main/java/com/fade/feed/repository/impl/FeedRepositoryImpl.java
  src/main/java/com/fade/feed/service/FeedService.java
Labels: enhancement

#105 refactor: archiving-dto 데이터 추가
  src/main/java/com/fade/faparchiving/dto/response/FindFapArchivingResponse.java
  src/main/java/com/fade/faparchiving/service/FapArchivingService.java
Labels: enhancement

#106 refactor: member dto fapSelectedCount 추가
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryCustom.java
  src/main/java/com/fade/faparchiving/repository/FapArchivingRepositoryImpl.java
  src/main/java/com/fade/member/dto/response/FindMemberDetailResponse.java
  src/main/java/com/fade/member/service/MemberService.java
Labels: enhancement

#107 fix: 무한스크롤 커서 오류 수정
  src/main/java/com/fade/feed/repository/impl/FeedRepositoryImpl.java
  src/main/java/com/fade/feed/service/FeedService.java
Labels: bug, enhancement

#108 feat: 멤버 상세 DTO 추가, 멤버 조회 서비스 오류 해결, introduceContent 수정 Service 로직 추가
  src/main/java/com/fade/member/controller/MemberController.java
  src/main/java/com/fade/member/dto/request/ModifyMemberRequest.java
  src/main/java/com/fade/member/dto/response/FindMemberDetailResponse.java
  src/main/java/com/fade/member/dto/response/FindMyMemberDetailResponse.java
  src/main/java/com/fade/member/entity/Member.java
  src/main/java/com/fade/member/service/MemberService.java
  src/main/java/com/fade/subscribe/dto/request/CountSubscriberRequest.java
Labels: bug, enhancement, feature

#109 fix: 피드 없을 때 커서 index error 수정
  src/main/java/com/fade/feed/service/FeedService.java
Labels: bug, enhancement

#110 fix: 구독자 조회 스크롤 커서 수정
  src/main/java/com/fade/subscribe/repository/SubscribeRepositoryCustom.java
  src/main/java/com/fade/subscribe/repository/SubscribeRepositoryImpl.java
  src/main/java/com/fade/subscribe/service/SubscribeService.java
Labels: bug, enhancement

#111 refactor: 멤버 검색 dto 멤버 id 추가
  src/main/java/com/fade/member/controller/MemberController.java
  src/main/java/com/fade/member/dto/response/MemberSearchItemResponse.java
  src/main/java/com/fade/member/dto/response/MemberSearchResponse.java
  src/main/java/com/fade/member/service/MemberService.java
Labels: enhancement

#112 fix: subscribe시 createdAt null 인 버그 수정
  src/main/java/com/fade/subscribe/entity/Subscribe.java
Labels: enhancement
